// ============================================================
// OATH — Mock Data for UI Development
// ============================================================

import type {
  Profile,
  Wallet,
  Oath,
  WallEntry,
  Transaction,
} from "./types";

// ---- Current User ----
export const mockProfile: Profile = {
  id: "u-001",
  username: "reaper_exe",
  display_name: "Aryan",
  oaths_created: 14,
  oaths_completed: 9,
  oaths_failed: 3,
  total_staked: 4250.0,
  total_lost: 750.0,
  total_won: 1800.0,
  reputation_score: 82,
  loss_streak: 0,
  penalty_box_until: null,
  created_at: "2025-01-15T00:00:00Z",
};

export const mockWallet: Wallet = {
  id: "w-001",
  user_id: "u-001",
  balance: 1247.5,
  escrow_locked: 500.0,
  total_deposited: 5000.0,
  total_withdrawn: 2000.0,
};

// ---- Other Users ----
const mockUsers: Profile[] = [
  {
    id: "u-002",
    username: "ghost_protocol",
    display_name: "Reza",
    oaths_created: 22,
    oaths_completed: 18,
    oaths_failed: 2,
    total_staked: 8400.0,
    total_lost: 200.0,
    total_won: 4200.0,
    reputation_score: 95,
    loss_streak: 0,
    penalty_box_until: null,
    created_at: "2025-02-01T00:00:00Z",
  },
  {
    id: "u-003",
    username: "void_walker",
    display_name: "Maya",
    oaths_created: 8,
    oaths_completed: 3,
    oaths_failed: 5,
    total_staked: 2100.0,
    total_lost: 1500.0,
    total_won: 300.0,
    reputation_score: 45,
    loss_streak: 2,
    penalty_box_until: null,
    created_at: "2025-03-10T00:00:00Z",
  },
  {
    id: "u-004",
    username: "iron_oath",
    display_name: "Kai",
    oaths_created: 31,
    oaths_completed: 28,
    oaths_failed: 1,
    total_staked: 12000.0,
    total_lost: 100.0,
    total_won: 7500.0,
    reputation_score: 98,
    loss_streak: 0,
    penalty_box_until: null,
    created_at: "2024-11-20T00:00:00Z",
  },
  {
    id: "u-005",
    username: "deadweight",
    display_name: "Jess",
    oaths_created: 6,
    oaths_completed: 1,
    oaths_failed: 5,
    total_staked: 3000.0,
    total_lost: 2800.0,
    total_won: 0.0,
    reputation_score: 12,
    loss_streak: 3,
    penalty_box_until: new Date(Date.now() + 5 * 24 * 3600 * 1000).toISOString(),
    created_at: "2025-05-01T00:00:00Z",
  },
  {
    id: "u-006",
    username: "silent_vow",
    display_name: "Tomas",
    oaths_created: 15,
    oaths_completed: 11,
    oaths_failed: 3,
    total_staked: 5500.0,
    total_lost: 900.0,
    total_won: 2800.0,
    reputation_score: 76,
    loss_streak: 0,
    penalty_box_until: null,
    created_at: "2025-01-28T00:00:00Z",
  },
];

// ---- Active Oaths ----
export const mockActiveOaths: Oath[] = [
  {
    id: "o-001",
    creator_id: "u-001",
    creator: mockProfile,
    oath_statement: "Run 5km every morning for 30 days",
    deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    oath_type: "solo",
    verification_method: "nominee",
    consequence_type: "fiat",
    stake_amount: 500.0,
    status: "active",
    min_players: 1,
    max_players: 1,
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "o-002",
    creator_id: "u-001",
    creator: mockProfile,
    oath_statement: "Ship MVP by end of month",
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    oath_type: "duo",
    verification_method: "peer",
    consequence_type: "fiat",
    stake_amount: 250.0,
    status: "active",
    min_players: 2,
    max_players: 2,
    opponent_id: "u-002",
    opponent: mockUsers[0],
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "o-003",
    creator_id: "u-002",
    creator: mockUsers[0],
    nominee_email: "@" + mockProfile.username,
    oath_statement: "Write 10,000 words on distributed systems",
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    oath_type: "solo",
    verification_method: "nominee",
    consequence_type: "fiat",
    stake_amount: 100.0,
    status: "active",
    min_players: 1,
    max_players: 1,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    proofs: [
      {
        id: "p-001",
        oath_id: "o-003",
        submitted_by: "u-002",
        proof_type: "link",
        proof_url: "https://github.com/example/distributed-draft",
        proof_text: "Finished drafts for Chapters 4 & 5. Submitted pull request #14.",
        status: "pending_review",
        review_deadline: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(),
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "o-004",
    creator_id: "u-002",
    creator: mockUsers[0],
    oath_statement: "Run 10km under 50 minutes Duel",
    deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    oath_type: "duo",
    verification_method: "peer",
    consequence_type: "shared_oath",
    stake_amount: 150.0,
    status: "active",
    min_players: 2,
    max_players: 2,
    opponent_id: "u-001",
    opponent: mockProfile,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    proofs: [
      {
        id: "p-002",
        oath_id: "o-004",
        submitted_by: "u-002",
        submitter: mockUsers[0],
        proof_type: "photo",
        proof_url: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&auto=format&fit=crop&q=80",
        proof_text: "Garmin 10k finished in 48:32. Check GPS pace split and heart rate.",
        status: "pending_review",
        review_deadline: new Date(Date.now() + 19 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
];

// ---- Squad Pool Lobbies ----
export const mockSquadOaths: Oath[] = [
  {
    id: "o-010",
    creator_id: "u-004",
    creator: mockUsers[2],
    oath_statement: "Complete 100 pushups daily for 2 weeks",
    deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    oath_type: "lobby",
    verification_method: "quorum",
    consequence_type: "fiat",
    stake_amount: 100.0,
    status: "pending",
    min_players: 5,
    max_players: 8,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    members: [
      { id: "gm-1", oath_id: "o-010", user_id: "u-004", user: mockUsers[2], stake_amount: 100, status: "joined", proof_submitted: false, votes_received: 0, votes_needed: 3, is_active_participant: false },
      { id: "gm-2", oath_id: "o-010", user_id: "u-002", user: mockUsers[0], stake_amount: 100, status: "joined", proof_submitted: false, votes_received: 0, votes_needed: 3, is_active_participant: false },
      { id: "gm-3", oath_id: "o-010", user_id: "u-006", user: mockUsers[4], stake_amount: 100, status: "joined", proof_submitted: false, votes_received: 0, votes_needed: 3, is_active_participant: false },
    ],
  },
  {
    id: "o-011",
    creator_id: "u-002",
    creator: mockUsers[0],
    oath_statement: "Read 1 book per week for a month",
    deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
    oath_type: "lobby",
    verification_method: "quorum",
    consequence_type: "fiat",
    stake_amount: 75.0,
    status: "pending",
    min_players: 5,
    max_players: 6,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    members: [
      { id: "gm-4", oath_id: "o-011", user_id: "u-002", user: mockUsers[0], stake_amount: 75, status: "joined", proof_submitted: false, votes_received: 0, votes_needed: 3, is_active_participant: false },
      { id: "gm-5", oath_id: "o-011", user_id: "u-003", user: mockUsers[1], stake_amount: 75, status: "joined", proof_submitted: false, votes_received: 0, votes_needed: 3, is_active_participant: false },
    ],
  },
  {
    id: "o-012",
    creator_id: "u-006",
    creator: mockUsers[4],
    oath_statement: "Cold shower every morning — no exceptions",
    deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    oath_type: "lobby",
    verification_method: "quorum",
    consequence_type: "combined",
    stake_amount: 200.0,
    status: "active",
    min_players: 5,
    max_players: 5,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    proofs: [
      {
        id: "p-012-1",
        oath_id: "o-012",
        submitted_by: "u-006",
        submitter: mockUsers[4],
        proof_type: "photo",
        proof_url: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=800&auto=format&fit=crop&q=80",
        proof_text: "Took cold shower at 6:30am sharp. Thermometer reading 10°C.",
        status: "pending_review",
        review_deadline: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "p-012-2",
        oath_id: "o-012",
        submitted_by: "u-002",
        submitter: mockUsers[0],
        proof_type: "video",
        proof_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        proof_text: "Recorded ice cold plunge video evidence with timestamps.",
        status: "pending_review",
        review_deadline: new Date(Date.now() + 22 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "p-012-3",
        oath_id: "o-012",
        submitted_by: "u-004",
        submitter: mockUsers[2],
        proof_type: "link",
        proof_url: "https://strava.com/activities/coldshower",
        proof_text: "Heart rate monitor showing cold shock spike and recovery rhythm.",
        status: "pending_review",
        review_deadline: new Date(Date.now() + 15 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
      },
    ],
    members: [
      { id: "gm-6", oath_id: "o-012", user_id: "u-006", user: mockUsers[4], stake_amount: 200, status: "joined", proof_submitted: true, votes_received: 3, votes_needed: 3, is_active_participant: false },
      { id: "gm-7", oath_id: "o-012", user_id: "u-002", user: mockUsers[0], stake_amount: 200, status: "joined", proof_submitted: true, votes_received: 2, votes_needed: 3, is_active_participant: false },
      { id: "gm-8", oath_id: "o-012", user_id: "u-003", user: mockUsers[1], stake_amount: 200, status: "joined", proof_submitted: false, votes_received: 0, votes_needed: 3, is_active_participant: false },
      { id: "gm-9", oath_id: "o-012", user_id: "u-004", user: mockUsers[2], stake_amount: 200, status: "joined", proof_submitted: true, votes_received: 4, votes_needed: 3, is_active_participant: false },
      { id: "gm-10", oath_id: "o-012", user_id: "u-001", user: mockProfile, stake_amount: 200, status: "joined", proof_submitted: false, votes_received: 0, votes_needed: 3, is_active_participant: false },
    ],
  },
];

// ---- Wall of Shame ----
export const mockWallOfShame: WallEntry[] = [
  {
    id: "ws-001",
    oath_id: "o-100",
    user_id: "u-005",
    wall_type: "shame",
    oath_statement: "Wake up at 5am every day for a month",
    stake_amount: 500.0,
    excuse: "My alarm didn't go off... for 12 days straight",
    username: "deadweight",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ws-002",
    oath_id: "o-101",
    user_id: "u-003",
    wall_type: "shame",
    oath_statement: "No sugar for 60 days",
    stake_amount: 300.0,
    excuse: "It was my birthday cake, it doesn't count",
    username: "void_walker",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ws-003",
    oath_id: "o-102",
    user_id: "u-005",
    wall_type: "shame",
    oath_statement: "Publish 1 article per week",
    stake_amount: 200.0,
    excuse: "I had writers block for 3 weeks",
    username: "deadweight",
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ws-004",
    oath_id: "o-103",
    user_id: "u-003",
    wall_type: "shame",
    oath_statement: "Gym 6x/week for 90 days",
    stake_amount: 1000.0,
    excuse: "I pulled my hamstring... on day 3",
    username: "void_walker",
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ws-005",
    oath_id: "o-104",
    user_id: "u-005",
    wall_type: "shame",
    oath_statement: "No social media for 2 weeks",
    stake_amount: 150.0,
    excuse: "I needed to check one DM and then... 3 hours later",
    username: "deadweight",
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ws-006",
    oath_id: "o-105",
    user_id: "u-003",
    wall_type: "shame",
    oath_statement: "Meditate 20 min daily",
    stake_amount: 100.0,
    excuse: "I fell asleep every single time",
    username: "void_walker",
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// ---- Wall of Honor ----
export const mockWallOfHonor: WallEntry[] = [
  {
    id: "wh-001",
    oath_id: "o-200",
    user_id: "u-004",
    wall_type: "honor",
    oath_statement: "100 days of code — shipped 3 products",
    stake_amount: 2000.0,
    username: "iron_oath",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "wh-002",
    oath_id: "o-201",
    user_id: "u-002",
    wall_type: "honor",
    oath_statement: "Marathon in under 4 hours",
    stake_amount: 1500.0,
    username: "ghost_protocol",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "wh-003",
    oath_id: "o-202",
    user_id: "u-004",
    wall_type: "honor",
    oath_statement: "Zero alcohol for 6 months",
    stake_amount: 3000.0,
    username: "iron_oath",
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "wh-004",
    oath_id: "o-203",
    user_id: "u-006",
    wall_type: "honor",
    oath_statement: "Saved $10,000 emergency fund",
    stake_amount: 500.0,
    username: "silent_vow",
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "wh-005",
    oath_id: "o-204",
    user_id: "u-002",
    wall_type: "honor",
    oath_statement: "Published thesis — 18 months of discipline",
    stake_amount: 5000.0,
    username: "ghost_protocol",
    created_at: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// ---- Transactions ----
export const mockTransactions: Transaction[] = [
  { id: "t-001", wallet_id: "w-001", oath_id: "o-001", type: "escrow_lock", amount: 500, description: "Locked for: Run 5km every morning", created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString() },
  { id: "t-002", wallet_id: "w-001", type: "deposit", amount: 1000, description: "Wallet deposit", created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString() },
  { id: "t-003", wallet_id: "w-001", oath_id: "o-099", type: "reward", amount: 450, description: "Won: Complete portfolio site", created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString() },
  { id: "t-004", wallet_id: "w-001", oath_id: "o-098", type: "penalty", amount: 250, description: "Failed: No junk food for 30 days", created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString() },
  { id: "t-005", wallet_id: "w-001", type: "deposit", amount: 2000, description: "Wallet deposit", created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString() },
];
